---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/demo/nginx:latest

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /pod
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
          - path: /pod1
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
