name: Create Autopilot Cluster

on:
  workflow_dispatch:
    inputs:
      app_nodes:
        description: 'Number of app nodes'
        required: true
        default: '3' # You can change the default value as needed

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true


    - name: Create Regional Autopilot Cluster
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        APP_NODES: ${{ github.event.inputs.app_nodes }}
      run: |
        gcloud container clusters create-auto backup \                                                                                                                  1 ↵  2635  16:28:57
            --region=us-central1\
            --project=$GOOGLE_PROJECT