name: Create GKE Cluster

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  create-autopilot-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: update gcloud
        run: |
          gcloud components update


      - name: Create GKE Cluster
        run: |
          # Your command to create the GKE cluster goes here
          gcloud container clusters create example-cluster \
          --zone us-central1-a \
          --node-locations us-central1-a,us-central1-b,us-central1-c

      # Additional steps to configure and use the Autopilot GKE cluster

