name: Create GKE Cluster

on:
  workflow_dispatch:
    inputs:
      app_nodes:
        description: 'Number of app nodes'
        required: true
        default: '3' # change the default value as needed
      zone_area:
        description: 'Zone'
        required: true
        default: 'us-central1-a'
      cluster_name:
        description: 'Name of the Autopilot cluster'
        required: true
        default: 'backup' # Default cluster name, change it when needed

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true


    - name: Create Regional Autopilot Cluster
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
        APP_NODES: ${{ github.event.inputs.app_nodes }}
        ZONE_AREA: ${{ github.event.inputs.zone_area }}
      run: |
        gcloud container clusters create $CLUSTER_NAME \
            --zone $ZONE_AREA \
            --node-locations us-central1-a,us-central1-b,us-central1-c